# Generated by Django 3.1.3 on 2020-11-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huser',
            name='contact_phone2',
        ),
        migrations.RemoveField(
            model_name='huser',
            name='contact_phone3',
        ),
        migrations.RemoveField(
            model_name='huser',
            name='reg_plate2',
        ),
    ]
